### ISSUE TITLE
NLP stack not working - open-bot-data stack not working

### ISSUE THREAD

**Issue by lisaMartini** [voyages-sncf-technologies/tock-docker#12]
Hi, 

I'm a windows user and I'm trying to launch the NLP stack with the following command : 

 `#get the last docker-compose file
   curl -o docker-compose.yml https://raw.githubusercontent.com/voyages-sncf-technologies/tock-docker/master/docker-compose.yml
   #get the last tag
   curl -o .env https://raw.githubusercontent.com/voyages-sncf-technologies/tock-docker/master/.env
   #launch the stack
   docker-compose up`

I got several issues related to connections :

- **Kotlin illegal reflective access**

![kotlin illegal reflective access](https://user-images.githubusercontent.com/44759708/49368164-0090a780-f729-11e8-823e-80bcd86decb2.PNG)

- **Mongo connection refused**
![mongo host unreachable connection refused](https://user-images.githubusercontent.com/44759708/49368239-2322c080-f729-11e8-9b12-178f01491298.PNG)

Do you have any clue about what I should do ? I tried to run the bot-open-data but without the NLP stack working nothing works.

Thank you for your help

**Comment by vsct-jburet** [comment]
@lisaMartini sorry for the answer delay. Please ask questions like this with gitter https://gitter.im/tockchat/Lobby

- the warnings are "normal" netty warnings - you can ignore
- Have you read this paragraph:

> Windows users, you need to run dos2unix to format the mongo setup script first:
> dos2unix ./scripts/setup.sh

We are going to release a 2.0.0 version tomorrow. It should fix all windows errors
