### ISSUE TITLE
mongo wont start with --bind_ip_all command

### ISSUE THREAD

**Issue by booleon** [voyages-sncf-technologies/tock-docker#4]
Hello, 
I'm trying to test your bot and I found out that the command "--bind_ip_all" you are using for mongo in your docker-compose is not compatible anymore with the latest version of mongo.
You should whether remove it (it is now default open to any IP) or fix your mongo version.
regards,
Florimond

**Comment by vsct-jburet** [comment]
@booleon --bind_ip_all is new in mongo 3.6. See https://docs.mongodb.com/manual/reference/program/mongod/ 

So you need to pull the last mongo image and it should be ok. Please reopen the issue if you still have the issue
