### ISSUE TITLE
mongo does not start on windows

### ISSUE THREAD

**Issue by McFoggy** [voyages-sncf-technologies/tock-docker#5]
_**Disclaimer**: This is not an issue with [tock](https://voyages-sncf-technologies.github.io/tock), but more a hint for your trial users ; directly close the issue and/or tag it as documentation at your convenience and thanks for providing [tock](https://voyages-sncf-technologies.github.io/tock)._

## Environment:
- OS: 
`Windows 10 version 1709`
- Docker:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

## Problem
`mongo` fails to start with an error containing
```
connection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
```

There are several issues regarding volumes on windows ; but the easiest to proceed with the [Getting Started](https://voyages-sncf-technologies.github.io/tock/en/getting-started/) guide is just to remove the mongo exposed volume from the docker-compose.yml file.

**Comment by lusubelli** [comment]
Hello @McFoggy, on windows you must specify the volume path in your user directory.
Something like that : 

```sh
volumes:
      - c:\users\tockmongo:/data/db
```

Best regards
