### ISSUE TITLE
How to test Open Data Bot in local mode

### ISSUE THREAD

**Issue by LGnord** [voyages-sncf-technologies/tock-docker#9]
Dear all,

I would like to run the Open Data Bot example with a google home. I follow all the steps described in the README.

I manage to update my actions on google with gaction. Then I try the google simulator. But I allays got errors about my server. Google touch it since I have logs in ngrok.io. But it is an error:
`POST /ga/bot_open_data         404 Not Found` 

So I guess that the problem is on machine. Indeed, when quering localhost:8080/ga/bot_open_data
`Resource not found`

Moreover the port 8080 is in use:
`tcp6       0      0 :::8080                 :::*                    LISTEN      15100/docker-proxy`

How to check that my bot in running on my machine? How to debug the bot in local mode?

Thanks for your help.

**Comment by vsct-jburet** [comment]
Please check that the "relative REST path" of your bot configuration is /ga/bot-open-data, like in this screenshot: 

![image](https://user-images.githubusercontent.com/12413454/44053856-2f18dcf2-9f41-11e8-86a4-e6360a6f9855.png)

**Comment by LGnord** [comment]
Thanks a lot.
